### ISSUE TITLE
VK auth not open (Android)

### ISSUE THREAD

**Issue by TarasovMV** [BazuMax/capacitor-plugin-vk-auth#1]
I have a problem with connect this library.I made all steps from instruction and this library not work for me. When I start method there is no any window or error messages in console (only 2 standard messages with id and scope). Can you help me resolve this issue?

P.S. Angular 10 + Ionic 5 (capacitor)

strings.xml

```
<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="app_name">luc-ionic</string>
    <string name="title_activity_main">luc-ionic</string>
    <string name="package_name">io.ionic.starter</string>
    <string name="custom_url_scheme">io.ionic.starter</string>

    <integer name="com_vk_sdk_AppId">7731427</integer>
</resources>
```

```
package io.ionic.starter;
import android.os.Bundle;
import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;
import java.util.ArrayList;
import com.ahm.capacitor.camera.preview.CameraPreview;
import com.bazumax.plugins.vk.VKAuth;

public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
      add(CameraPreview.class);
      add(VKAuth.class);
    }});
  }
}
```

Method
```
public async authRequestPlugin(): Promise<void> {
        await VKAuth.initWithId({ id: '7731427' });
        await VKAuth.auth({ scope: ['offline'] });
        VKAuth.addListener('vkAuthFinished', (info) => {
            console.log('vkAuthFinished was fired', JSON.stringify(info, null, 2));
        });
    }
```

vk settings
![image](https://user-images.githubusercontent.com/31613333/104854599-ae1aa100-5918-11eb-86d6-6ba57f06484d.png)

**Comment by bazuka5801** [comment]
Hi :)
Hmm... Please, check your Android Studio Run Log, when you open auth dialog.

**Comment by TarasovMV** [comment]
Only that:
```
D/Capacitor: Registering plugin: VKAuth
...
I/Capacitor/Console: File: http://localhost/main-es2015.js - Line 263 - Msg: auth
I/Capacitor/Console: File: http://localhost/vendor-es2015.js - Line 42351 - Msg: ECHO [object Object]
    File: http://localhost/vendor-es2015.js - Line 42357 - Msg: ECHO [object Object]
```

Full log:
[log.txt](https://github.com/BazuMax/capacitor-plugin-vk-auth/files/5844779/log.txt)

**Comment by bazuka5801** [comment]
@TarasovMV
Message "ECHO [object Object]" not full log, can you expand object, which console output?
Can you share example with your basic app + vk auth template?
May be problems:
1) Invalid certificate
2) Invalid vk app settings in vk.com
3) After registering full log output that Unable to read file at path public/plugins
```log
D/Capacitor: Registering plugin: VKAuth
E/Capacitor: Unable to read file at path public/plugins
```

**Comment by TarasovMV** [comment]
Message "ECHO [object Object]"
```
Msg: init {"value":"7731427"}
Msg: scope {"value":{"scope":["offline"]}}
```
Certificate is valid, google auth work good.
repo: https://github.com/TarasovMV/luc-ionic

**Comment by bazuka5801** [comment]
> Message "ECHO [object Object]"
> 
> ```
> Msg: init {"value":"7731427"}
> Msg: scope {"value":{"scope":["offline"]}}
> ```
> 
> Certificate is valid, google auth work good.
> repo: https://github.com/TarasovMV/luc-ionic

Thanx! This evening I will try implement VK Auth

**Comment by bazuka5801** [comment]
@TarasovMV I fixed bug, you use web version plugin instead of capacitor in your service, after change it, it works!
https://github.com/TarasovMV/luc-ionic/pull/1

**Comment by TarasovMV** [comment]
Thanks a lot!
