### ISSUE TITLE
Vk auth not working on iOS

### ISSUE THREAD

**Issue by fannyfan414** [BazuMax/capacitor-plugin-vk-auth#2]
Capacitor v3. 

Following the instructions, I create standalone application and add vkID to my app 
`    <key>CFBundleURLSchemes</key>
    <array>
        <string>capacitor</string>
        <string>vk723****</string>
    </array>`

When i try to log in i get an error "OAuth authorization cannot be used from native VK applications"

**Comment by bazuka5801** [comment]
@fannyfan414 Maybe you using "Site app" instead of "Standalone-application".
I will update the Readme
![image](https://user-images.githubusercontent.com/11452353/123266143-6968e680-d504-11eb-8e64-6c8fe5c662df.png)

**Comment by fannyfan414** [comment]
Apparently my carelessness.
The readme contains a sample code VKAuth.initWithId ({id: '7569443'}), but I used id as a number VKAuth.initWithId ({id: 723}).
Therefore, apparently id was not set and by default it was set as 123456
